kotlin.stdlib.default.dependency=false

org.gradle.workers.max=16
org.gradle.jvmargs=-Xms512m -Xmx8g


clionHome=C:/home/arcno/bin/CLion
clionRadler=plugins/clion-radler
clionCidrPSIBase=plugins/clion/lib/modules/intellij.cidr.psi.base.jar
clionRdIdeModels=lib/modules/intellij.rd.ide.model.generated.jar
clionRdPlatform=lib/modules/intellij.rd.platform.jar