# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency=false
# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.vfs.watch=true

org.gradle.workers.max=16
org.gradle.jvmargs=-Xms512m -Xmx8g -XX:MaxMetaspaceSize=1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:+PerfDisableSharedMem -XX:+UseStringDeduplication -Dfile.encoding=UTF-8

kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.daemon.jvmargs=-Xms256m -Xmx4g -XX:+UseG1GC -Dfile.encoding=UTF-8


org.gradle.caching.debug=false
org.gradle.cache.local=true
org.gradle.cache.local.directory=.gradle/build-cache
org.gradle.cache.local.removeUnusedEntriesAfterDays=14

# Console/diagnostics (optional)
org.gradle.console=rich
#org.gradle.logging.stacktrace=short

CLionVersion=2025.2
CLionHome=C:\\home\\arcno\\bin\\CLion
rustPlugin=com.jetbrains.rust:252.23892.452
psiViewerPlugin=PsiViewer:252.23892.248